name: Publish to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check if user is repo owner
        run: |
          if [[ "${{ github.actor }}" != "${{ github.repository_owner }}" ]]; then
            echo "::error::このワークフローはリポジトリ所有者のみ実行できます"
            exit 1
          fi

      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and Publish with Gradle
        run: ./gradlew build publish -PskipSigning=true
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_OPTS: "--overwrite"

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: Plugin-JAR
          path: build/libs/*.jar
          if-no-files-found: error
          retention-days: 90
